### ISSUE TITLE
Conflict w/ Gulp's Default Watch

### ISSUE THREAD

**Issue by jhartman86** [JacksonGariety/gulp-nodemon#26]
Running into an issue where gulp watch (built-in version, not npm's gulp-watch) won't work in tandem with gulp-nodemon. Neither tasks fail outright (and gulp-nodemon actually does restart the server OK), but gulp watch won't write file changes.

Post on stack overflow looking for help as well: http://stackoverflow.com/questions/23506545/gulp-watch-and-nodemon-conflict. (Explained with code sample and in more detail there). Posting here as I haven't gotten any responses or found answers on the interwebs.

That said, thanks for the great work Jackson. Everything else works like a charm.

**Comment by JacksonGariety** [comment]
@lzrski this is a nodemon issue I'm hoping is fixed in 1.3.0

@ghidello you can do what you're doing entirely within gulp-nodemon if you wish. From what I can see it should be as simple as appending an `.on('change', ['scripts'])` to the gulp-nodemon call. It's explained well in OP's SO question: http://stackoverflow.com/questions/23506545/gulp-watch-and-nodemon-conflict

@jhartman86 looks like the answer is in your SO question so I'll close this.
